branches:
  only:
  - dev
  - ci

addons:
  ssh_known_hosts: dev.bump.fm

language: node_js
node_js: node

install:
- npm install

script:
- npm run build

after_success:
- openssl aes-256-cbc -K $encrypted_04a81a03299c_key -iv $encrypted_04a81a03299c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- rsync -e "ssh -i /tmp/deploy_rsa" -avihr build ubuntu@dev.bump.fm:/home/ubuntu/dev.pitchday.io/

